-
  name: Play1
  hosts: all
  tasks:
    - name: Display resolv.conf contents
      command: cat resolv.conf chdir=/etc
      register: command_output

    - name: Print to console
      debug: msg = "{{command_output.stdout}}"

    - name: create a file on remote machine
      file:
        dest: /tmp/myfile
        state: '{{file_state}}'
