---
- name: Install Jenkins
  hosts: target1
  gather_facts: false
  become: true
  tags:
   - download-jenkins
  tasks:
    - name: install wget and openjdk
      yum:
       name:
        - wget
        - java-1.8.0-openjdk
    
    - name: download jenkins repo
      get_url:
       url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
       dest: /etc/yum.repos.d/jenkins.repo

    - name: import jenkins keys
      rpm_key:
       state: present
       key: https://jenkins-ci.org/redhat/jenkins-ci.org.key


- name: Start Jenkins
  hosts: target1
  gather_facts: false
  become: true
  tags:
   - install-jenkins
  tasks:
    - name: install jenkins yum repo
      yum:
       name: jenkins
       state: present
    
    - name: Start and Enable Jenkins
      systemd:
       name: jenkins
       state: started
       enabled: true

- name: Unlock jenkins admin
  hosts: target1
  tags:
   - jenkins-password
  tasks:
    - name: get init jenkins password
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      become: true
      change_when: false
      register: result
    
    - name: print init password Jenkins
      debug:
       var: result.stdout
  

