#!/bin/bash
FILE="/home/external/alex/test/test.txt"
echo "**** File - $FILE contents ***"
cat $FILE
#x='cat test.txt | wc -l'
x=$(cat test.txt | wc -l)
echo "***You have $x line in your file ***"
#echo "Please give the number: "
#echo "........"
#read number
#result=$(grep -in "$number" "$FILE")
#echo $result
result=$(grep -on "[0-9]\+" "$FILE")
echo $result
cuvinte=$(grep -o "[0-9]\+" "$FILE" | wc -w)
echo "*** You have $cuvinte numbers in your file ****"
echo "------------------------------------------"
result1=$(grep -o "[0-9]\+" "$FILE")
echo $result1 | tr -s ' ' '\n' > numbers.txt
FILE1="/home/external/alex/test/numbers.txt"
#NUMS=$(cat numbers.txt)
#echo "$NUMS"
#for NUM in $NUMS
#	do echo "NUM"
#done
